name: DSP
 
channels:
  - default
dependencies:
  - jupyter
  - notebook
  - nbconvert
  - ipywidgets
  - jupyterlab>=4.2
  - jupyterlab_widgets
  - matplotlib>=3.9
  - numpy>=1.26
  - scipy>=1.14
  - pandas>=1.5
  - seaborn>=0.3
