name: DSP-2627
 
channels:
  - default
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python>=3.14
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyterlab_widgets
  - nbconvert
  - matplotlib
  - numpy
  - scipy
  - pandas
  - seaborn
